### ISSUE TITLE
Por qué un curso tiene tantos repositorios

### ISSUE THREAD

**Issue by aasanchez** [0utKast/angular34#1]
Apreciado profesor, toda mi vida le agradeceré sus cursos, ha Sido una pieza clave en mi aprendizaje por anos, sin embargo debo sugerirle que está.haciendo algo muy malo al crear un repo por vídeo por curso, cosa que fácilmente podría manejar con git tags o versiones, incluso allí tiene la posibilidad de cargar binarios como un archivo .rar, me gustaría entender por qué tomo esta vía tan extraño poco común, y si por alguna razón yo puedo ayudarlo en algo sería todo un honor.

**Comment by 0utKast** [comment]
En cada videotutorial se trata un tema. En alguno puede ser que se
reutilice el mismo proyecto, pero en otros son materiales totalmente
diferentes, por lo que no tendría sentido incluirlos dentro de un mismo
proyecto.
